version: '3.8'

services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hospital-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
      - ./hospital_management.sql:/docker-entrypoint-initdb.d/hospital_management.sql
    networks:
      - hospital-net

volumes:
  dbdata:

networks:
  hospital-net: